"""index error

Revision ID: aed713c6b0b0
Revises: ccdffadbf888
Create Date: 2021-04-21 15:58:55.433928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aed713c6b0b0'
down_revision = 'ccdffadbf888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    # ### end Alembic commands ###
